[pytest]
pythonpath = .
addopts = --alluredir allure-results --clean-alluredir
markers =
    ui: mark a test as a UI test.
    api: mark a test as an API test.
    api_user: mark a test as an API test related to user operations.
